### ISSUE TITLE
Input-remapper not working after python3-evdev update on Fedora 41 (2.0.1 latest available)

### ISSUE THREAD

**Issue by penguinbait** [sezanzeb/input-remapper#1074]
After updating from python3-evdev 1.7.1-2.fc41 to 1.9.0-1.fc41 input remapper stopped working correctly.  

**FIX:
sudo dnf downgrade python3-evdev**

[3/4] Downgrading python3-evdev-0:1.7.1-2.fc41.x86_64            
[4/4] Removing python3-evdev-0:1.9.0-1.fc41.x86_64  

(base) snoopy@speedy:~/.config$ sudo input-remapper-gtk 
input-remapper-gtk 2.0.1  https://github.com/sezanzeb/input-remapper
python-evdev 1.9.0
Done
Connected to the service
Loaded config from "/home/snoopy/.config/input-remapper-2/config.json"
WARNING: HandlerDisabled entry failed: "nothing connected to <bound method CodeEditor._on_gtk_changed of <inputremapper.gui.components.editor.CodeEditor object at 0x7f0f981eef90>>"
WARNING: HandlerDisabled exit failed: "nothing connected to <bound method CodeEditor._on_gtk_changed of <inputremapper.gui.components.editor.CodeEditor object at 0x7f0f981eef90>>"
Found "DIERYA-DK63 3.0  Mouse", "EasySMX EasySMX X10", "Logitech G502 HERO Gaming Mouse"
Loading group "DIERYA-DK63 3.0  Mouse"
Loading preset "new preset"
Loading preset from "/home/snoopy/.config/input-remapper-2/presets/DIERYA-DK63 3.0  Mouse/new preset.json"
Found "DIERYA-DK63 3.0  Mouse", "EasySMX EasySMX X10", "Logitech G502 HERO Gaming Mouse"
Loading group "EasySMX EasySMX X10"
Loading preset "URT_EASYSMX_DINPUT-copy"
Loading preset from "/home/snoopy/.config/input-remapper-2/presets/EasySMX EasySMX X10/URT_EASYSMX_DINPUT-copy.json"
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/inputremapper/gui/components/device_groups.py", line 67, in _on_gtk_toggle
    self._controller.load_group(self.group_key)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/inputremapper/gui/controller.py", line 481, in load_group
    self.load_preset(self.get_a_preset())
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/inputremapper/gui/controller.py", line 485, in load_preset
    self.data_manager.load_preset(name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/site-packages/inputremapper/gui/data_manager.py", line 323, in load_preset
    self.publish_preset()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/inputremapper/gui/data_manager.py", line 111, in publish_preset
    self.message_broker.publish(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        PresetData(
        ^^^^^^^^^^^
            self.active_preset.name, self.get_mappings(), self.get_autoload()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        )
        ^
    )
    ^
  File "/usr/lib/python3.13/site-packages/inputremapper/gui/messages/message_broker.py", line 66, in publish
    self._publish_all()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/inputremapper/gui/messages/message_broker.py", line 91, in _publish_all
    self._publish(*self._messages.popleft())
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/inputremapper/gui/messages/message_broker.py", line 80, in _publish
    listener(data)
    ~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/site-packages/inputremapper/gui/controller.py", line 137, in _on_preset_changed
    mappings.sort(
    ~~~~~~~~~~~~~^
        key=lambda mapping: (
        ^^^^^^^^^^^^^^^^^^^^^
            mapping.format_name() or mapping.input_combination.beautify()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        )
        ^
    )
    ^
  File "/usr/lib/python3.13/site-packages/inputremapper/gui/controller.py", line 139, in <lambda>
    mapping.format_name() or mapping.input_combination.beautify()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/inputremapper/configs/mapping.py", line 257, in format_name
    return self.input_combination.beautify()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/inputremapper/configs/input_config.py", line 434, in beautify
    return " + ".join(event.description(exclude_threshold=True) for event in self)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/inputremapper/configs/input_config.py", line 434, in <genexpr>
    return " + ".join(event.description(exclude_threshold=True) for event in self)
                      ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/inputremapper/configs/input_config.py", line 125, in description
    f"{self._get_name()} "
       ~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/inputremapper/configs/input_config.py", line 155, in _get_name
    key_name = key_name.replace("ABS_Z", "Trigger Left")
               ^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'replace'

**Comment by entroversal** [comment]
I am getting this same error in Fedora 41 KDE Wayland.

**Comment by Shr4pNull** [comment]
Same thing here, Nobara 41 Wayland. Any workarounds for this?

**Comment by penguinbait** [comment]
FIX:
sudo dnf downgrade python3-evdev

**Comment by penguinbait** [comment]
> On Fedora 41 KDE Wayland
> 
> ```
> ~$ input-remapper-gtk 
> Traceback (most recent call last):
>   File "/usr/bin/input-remapper-gtk", line 23, in <module>
>     from inputremapper.bin.input_remapper_gtk import InputRemapperGtkBin
>   File "/usr/lib/python3.13/site-packages/inputremapper/bin/input_remapper_gtk.py", line 31, in <module>
>     from inputremapper.bin.process_utils import ProcessUtils
>   File "/usr/lib/python3.13/site-packages/inputremapper/bin/process_utils.py", line 20, in <module>
>     import psutil
> ModuleNotFoundError: No module named 'psutil'
> ```
> 
> Either `sudo dnf builddep input-remapper` (installs 5 new packages), or installing `python3-psutil` separately will fix the above issue.
> 
> Edit: This seems to be an issue of Fedora package missing a dependency, not a problem in remapper itself. https://bugzilla.redhat.com/show_bug.cgi?id=2349938#c9

So you have this working with python3-evdev-0:1.9.0-1.fc41.x86_64 ?  My testing of all versions continues to fail unless I downgrade python3-evdev .

**Comment by sezanzeb** [comment]
input-remapper 2.1.1 supports python-evdev 1.9.0

**Comment by penguinbait** [comment]
It working now after Fedora updated the package.  Prior I tried the 2.1.1 from git and had same issue.  

Name            : input-remapper
Epoch           : 0
Version         : 2.1.1
Release         : 1.fc41
Architecture    : noarch
Installed size  : 1.9 MiB
Source          : input-remapper-2.1.1-1.fc41.src.rpm

**Comment by sezanzeb** [comment]
> Prior I tried the 2.1.1 from git and had same issue.

That might point to two parallel installations. https://github.com/sezanzeb/input-remapper/issues/895#issuecomment-2442470691 can help understanding what went wrong.

**Comment by kestutis-dambrauskas** [comment]
`sudo dnf install python3-psutil`

**Comment by dani7959** [comment]
Just stating that you no longer support the current versions of the package dependencies, which get installed as part of the normal OS update process, doesn't look like a completed issue.
Moreover, the python3-evdev 1.9.1 changelog doesn't seem to point to any breaking changes, just common sense fixes.
